import '../../data/models/hot_list_category.dart';

/// 默认榜单列表
class HotListData {
  static final List<HotListCategory> defaultCategories = [
    HotListCategory(
      name: 'bilibili',
      label: '哔哩哔哩',
      icon: 'assets/images/logo/bilibili.png',
      color: 0xFFFF6699,
      order: 0,
      show: true,
    ),
    HotListCategory(
      name: 'douyin',
      label: '抖音',
      icon: 'assets/images/logo/douyin.png',
      color: 0xFF000000,
      order: 1,
      show: true,
    ),
    HotListCategory(
      name: 'baidu',
      label: '百度',
      icon: 'assets/images/logo/baidu.png',
      color: 0xFF2932E1,
      order: 2,
      show: true,
    ),
    HotListCategory(
      name: 'tieba',
      label: '百度贴吧',
      icon: 'assets/images/logo/tieba.png',
      color: 0xFF3B5998,
      order: 3,
      show: true,
    ),
    HotListCategory(
      name: 'csdn',
      label: 'CSDN',
      icon: 'assets/images/logo/csdn.png',
      color: 0xFFFC5531,
      order: 4,
      show: true,
    ),
    HotListCategory(
      name: 'weibo',
      label: '微博',
      icon: 'assets/images/logo/weibo.png',
      color: 0xFFFF8200,
      order: 5,
      show: true,
    ),
    HotListCategory(
      name: 'zhihu',
      label: '知乎',
      icon: 'assets/images/logo/zhihu.png',
      color: 0xFF0084FF,
      order: 6,
      show: true,
    ),
    HotListCategory(
      name: '36kr',
      label: '36氪',
      icon: 'assets/images/logo/36kr.png',
      color: 0xFF1E90FF,
      order: 7,
      show: true,
    ),
    HotListCategory(
      name: 'sspai',
      label: '少数派',
      icon: 'assets/images/logo/sspai.png',
      color: 0xFFEC1C24,
      order: 8,
      show: true,
    ),
    HotListCategory(
      name: 'ithome',
      label: 'IT之家',
      icon: 'assets/images/logo/ithome.png',
      color: 0xFFD81E06,
      order: 9,
      show: true,
    ),
    HotListCategory(
      name: 'juejin',
      label: '稀土掘金',
      icon: 'assets/images/logo/juejin.png',
      color: 0xFF1E80FF,
      order: 10,
      show: true,
    ),
    HotListCategory(
      name: 'toutiao',
      label: '今日头条',
      icon: 'assets/images/logo/toutiao.png',
      color: 0xFFFF4040,
      order: 11,
      show: true,
    ),
    HotListCategory(
      name: 'thepaper',
      label: '澎湃新闻',
      icon: 'assets/images/logo/thepaper.png',
      color: 0xFF1A73E8,
      order: 12,
      show: true,
    ),
    HotListCategory(
      name: 'qq-news',
      label: '腾讯新闻',
      icon: 'assets/images/logo/qq-news.png',
      color: 0xFF0088FF,
      order: 13,
      show: true,
    ),
    HotListCategory(
      name: 'douban-movie',
      label: '豆瓣电影',
      icon: 'assets/images/logo/douban-movie.png',
      color: 0xFF00B51D,
      order: 14,
      show: true,
    ),
    HotListCategory(
      name: 'genshin',
      label: '原神',
      icon: 'assets/images/logo/genshin.png',
      color: 0xFFFFB600,
      order: 15,
      show: true,
    ),
    HotListCategory(
      name: 'lol',
      label: 'LOL',
      icon: 'assets/images/logo/lol.png',
      color: 0xFFCAA776,
      order: 16,
      show: true,
    ),
    HotListCategory(
      name: 'starrail',
      label: '崩坏：星穹铁道',
      icon: 'assets/images/logo/starrail.png',
      color: 0xFFFFD700,
      order: 17,
      show: true,
    ),
    HotListCategory(
      name: 'netease-news',
      label: '网易新闻',
      icon: 'assets/images/logo/netease-news.png',
      color: 0xFFD71A1B,
      order: 18,
      show: true,
    ),
    HotListCategory(
      name: 'weread',
      label: '微信读书',
      icon: 'assets/images/logo/weread.png',
      color: 0xFF07C160,
      order: 19,
      show: true,
    ),
    HotListCategory(
      name: 'douban-group',
      label: '豆瓣讨论小组',
      icon: 'assets/images/logo/douban-group.png',
      color: 0xFF00B51D,
      order: 20,
      show: true,
    ),
    HotListCategory(
      name: 'ngabbs',
      label: 'NGA',
      icon: 'assets/images/logo/ngabbs.png',
      color: 0xFF4F5F74,
      order: 21,
      show: true,
    ),
    HotListCategory(
      name: 'hellogithub',
      label: 'HelloGitHub',
      icon: 'assets/images/logo/hellogithub.png',
      color: 0xFF24292E,
      order: 22,
      show: true,
    ),
    HotListCategory(
      name: 'jianshu',
      label: '简书',
      icon: 'assets/images/logo/jianshu.png',
      color: 0xFFEA6F5A,
      order: 23,
      show: true,
    ),
    HotListCategory(
      name: 'zhihu-daily',
      label: '知乎日报',
      icon: 'assets/images/logo/zhihu-daily.png',
      color: 0xFF0084FF,
      order: 24,
      show: true,
    ),
    HotListCategory(
      name: '51cto',
      label: '51CTO',
      icon: 'assets/images/logo/51cto.png',
      color: 0xFFFF6700,
      order: 25,
      show: true,
    ),
    HotListCategory(
      name: 'acfun',
      label: 'AcFun',
      icon: 'assets/images/logo/acfun.png',
      color: 0xFFFD4C5D,
      order: 26,
      show: true,
    ),
    HotListCategory(
      name: 'coolapk',
      label: '酷安',
      icon: 'assets/images/logo/coolapk.png',
      color: 0xFF00C853,
      order: 27,
      show: true,
    ),
    HotListCategory(
      name: 'earthquake',
      label: '地震速报',
      icon: 'assets/images/logo/earthquake.png',
      color: 0xFFFF5722,
      order: 28,
      show: true,
    ),
    HotListCategory(
      name: 'history',
      label: '历史上的今天',
      icon: 'assets/images/logo/history.png',
      color: 0xFF795548,
      order: 29,
      show: true,
    ),
    HotListCategory(
      name: 'honkai',
      label: '崩坏3',
      icon: 'assets/images/logo/honkai.png',
      color: 0xFF6C63FF,
      order: 30,
      show: true,
    ),
    HotListCategory(
      name: 'hupu',
      label: '虎扑',
      icon: 'assets/images/logo/hupu.png',
      color: 0xFFFF6700,
      order: 31,
      show: true,
    ),
    HotListCategory(
      name: 'huxiu',
      label: '虎嗅',
      icon: 'assets/images/logo/huxiu.png',
      color: 0xFFFF6B00,
      order: 32,
      show: true,
    ),
    HotListCategory(
      name: 'ifanr',
      label: '爱范儿',
      icon: 'assets/images/logo/ifanr.png',
      color: 0xFFFF3B30,
      order: 33,
      show: true,
    ),
    HotListCategory(
      name: 'ithome-xijiayi',
      label: 'IT之家喜加一',
      icon: 'assets/images/logo/ithome-xijiayi.png',
      color: 0xFFD81E06,
      order: 34,
      show: true,
    ),
    HotListCategory(
      name: 'nodeseek',
      label: 'NodeSeek',
      icon: 'assets/images/logo/nodeseek.png',
      color: 0xFF00A67E,
      order: 35,
      show: true,
    ),
    HotListCategory(
      name: 'sina-news',
      label: '新浪新闻',
      icon: 'assets/images/logo/sina-news.png',
      color: 0xFFE60012,
      order: 36,
      show: true,
    ),
    HotListCategory(
      name: 'sina',
      label: '新浪',
      icon: 'assets/images/logo/sina.png',
      color: 0xFFE6162D,
      order: 37,
      show: true,
    ),
    HotListCategory(
      name: 'v2ex',
      label: 'V2EX',
      icon: 'assets/images/logo/v2ex.png',
      color: 0xFF333344,
      order: 38,
      show: true,
    ),
    HotListCategory(
      name: 'weatheralarm',
      label: '天气预警',
      icon: 'assets/images/logo/weatheralarm.png',
      color: 0xFF2196F3,
      order: 39,
      show: true,
    ),
    // 新增接口
    HotListCategory(
      name: '52pojie',
      label: '吾爱破解',
      icon: 'assets/images/logo/52pojie.png',
      color: 0xFF1E90FF,
      order: 40,
      show: true,
    ),
    HotListCategory(
      name: 'dgtle',
      label: '数字尾巴',
      icon: 'assets/images/logo/dgtle.png',
      color: 0xFF00B8D4,
      order: 41,
      show: true,
    ),
    HotListCategory(
      name: 'gameres',
      label: 'GameRes',
      icon: 'assets/images/logo/gameres.png',
      color: 0xFF3F51B5,
      order: 42,
      show: true,
    ),
    HotListCategory(
      name: 'geekpark',
      label: '极客公园',
      icon: 'assets/images/logo/geekpark.png',
      color: 0xFF00BCD4,
      order: 43,
      show: true,
    ),
    HotListCategory(
      name: 'github',
      label: 'GitHub',
      icon: 'assets/images/logo/github.png',
      color: 0xFF24292E,
      order: 44,
      show: true,
    ),
    HotListCategory(
      name: 'guokr',
      label: '果壳',
      icon: 'assets/images/logo/guokr.png',
      color: 0xFF8BC34A,
      order: 45,
      show: true,
    ),
    HotListCategory(
      name: 'hackernews',
      label: 'Hacker News',
      icon: 'assets/images/logo/hackernews.png',
      color: 0xFFFF6600,
      order: 46,
      show: true,
    ),
    HotListCategory(
      name: 'hostloc',
      label: 'HostLoc',
      icon: 'assets/images/logo/hostloc.png',
      color: 0xFF2196F3,
      order: 47,
      show: true,
    ),
    HotListCategory(
      name: 'kuaishou',
      label: '快手',
      icon: 'assets/images/logo/kuaishou.png',
      color: 0xFFFF5722,
      order: 48,
      show: true,
    ),
    HotListCategory(
      name: 'linuxdo',
      label: 'Linux.do',
      icon: 'assets/images/logo/linuxdo.png',
      color: 0xFFFFA500,
      order: 49,
      show: true,
    ),
    HotListCategory(
      name: 'miyoushe',
      label: '米游社',
      icon: 'assets/images/logo/miyoushe.png',
      color: 0xFF00BFA5,
      order: 50,
      show: true,
    ),
    HotListCategory(
      name: 'newsmth',
      label: '水木社区',
      icon: 'assets/images/logo/newsmth.png',
      color: 0xFF4CAF50,
      order: 51,
      show: true,
    ),
    HotListCategory(
      name: 'nytimes',
      label: '纽约时报',
      icon: 'assets/images/logo/nytimes.png',
      color: 0xFF000000,
      order: 52,
      show: true,
    ),
    HotListCategory(
      name: 'producthunt',
      label: 'Product Hunt',
      icon: 'assets/images/logo/producthunt.png',
      color: 0xFFDA552F,
      order: 53,
      show: true,
    ),
    HotListCategory(
      name: 'smzdm',
      label: '什么值得买',
      icon: 'assets/images/logo/smzdm.png',
      color: 0xFFE84142,
      order: 54,
      show: true,
    ),
    HotListCategory(
      name: 'yystv',
      label: '游研社',
      icon: 'assets/images/logo/yystv.png',
      color: 0xFF673AB7,
      order: 55,
      show: true,
    ),
  ];
}
